-- TeamAssist — controle op de databankstructuur (versie 0.19.0)
--
-- Plak dit in de D1-console na het uitvoeren van een schemawijziging. Het wijzigt
-- niets; het vergelijkt wat er staat met wat er hoort te staan.
--
-- Lees de bovenste regel: staat er ALLES OK, dan is de databank in orde. Staat er
-- een aantal, dan volgen daaronder de tabellen, indexen of kolommen die
-- ontbreken. Kolommen die er te veel zijn worden niet gemeld: die doen geen
-- kwaad en komen voor wanneer een oudere versie iets achterliet.
--
-- Dit bestand wordt gegenereerd uit schema.sql. Niet met de hand aanpassen —
-- draai 'node tools/genereer-controle.mjs' en er staat een test op.

WITH verwacht_object(soort, naam) AS (VALUES
  ('index', 'idx_aanwezigheden_activiteit'),
  ('index', 'idx_aanwezigheden_persoon'),
  ('index', 'idx_aanwezigheden_uniek'),
  ('index', 'idx_berichten_persoon'),
  ('index', 'idx_logboek_tijdstip'),
  ('index', 'idx_ouder_kind_kind'),
  ('index', 'idx_periodes_seizoen'),
  ('index', 'idx_personen_email'),
  ('index', 'idx_personen_relguid'),
  ('index', 'idx_rollen_persoon'),
  ('index', 'idx_rollen_uniek'),
  ('index', 'idx_taak_runs_taak'),
  ('index', 'idx_team_spelers_team'),
  ('index', 'idx_trainingen_reeks'),
  ('index', 'idx_trainingen_team'),
  ('index', 'idx_trainingsreeksen_team'),
  ('index', 'idx_wedstrijden_team'),
  ('index', 'idx_zaal_blokken_zaal'),
  ('index', 'idx_zaal_sluitingen_zaal'),
  ('table', 'aanmeldingen_wachtrij'),
  ('table', 'aanwezigheden'),
  ('table', 'accounts'),
  ('table', 'berichten'),
  ('table', 'instellingen'),
  ('table', 'logboek'),
  ('table', 'ouder_kind'),
  ('table', 'periodes'),
  ('table', 'personen'),
  ('table', 'rollen'),
  ('table', 'seizoenen'),
  ('table', 'taak_runs'),
  ('table', 'team_spelers'),
  ('table', 'teams'),
  ('table', 'trainingen'),
  ('table', 'trainingsreeksen'),
  ('table', 'wedstrijden'),
  ('table', 'wedstrijdselecties'),
  ('table', 'zaal_blokken'),
  ('table', 'zaal_sluitingen'),
  ('table', 'zalen')
),
verwacht_kolom(tabel, kolom) AS (VALUES
  ('aanmeldingen_wachtrij', 'sub'),
  ('aanmeldingen_wachtrij', 'email'),
  ('aanmeldingen_wachtrij', 'eerste_poging'),
  ('aanmeldingen_wachtrij', 'laatste_poging'),
  ('aanmeldingen_wachtrij', 'pogingen'),
  ('aanwezigheden', 'id'),
  ('aanwezigheden', 'soort'),
  ('aanwezigheden', 'activiteit_id'),
  ('aanwezigheden', 'team_guid'),
  ('aanwezigheden', 'seizoen'),
  ('aanwezigheden', 'persoon_id'),
  ('aanwezigheden', 'hoedanigheid'),
  ('aanwezigheden', 'opgave_status'),
  ('aanwezigheden', 'opgave_reden'),
  ('aanwezigheden', 'opgave_toelichting'),
  ('aanwezigheden', 'opgave_door'),
  ('aanwezigheden', 'opgave_tijdstip'),
  ('aanwezigheden', 'uitgesloten'),
  ('aanwezigheden', 'uitgesloten_reden'),
  ('aanwezigheden', 'uitgesloten_door'),
  ('aanwezigheden', 'uitgesloten_tijdstip'),
  ('aanwezigheden', 'vaststelling_status'),
  ('aanwezigheden', 'vaststelling_door'),
  ('aanwezigheden', 'vaststelling_tijdstip'),
  ('aanwezigheden', 'aangemaakt'),
  ('accounts', 'sub'),
  ('accounts', 'persoon_id'),
  ('accounts', 'email'),
  ('accounts', 'eerste_aanmelding'),
  ('accounts', 'laatste_aanmelding'),
  ('berichten', 'id'),
  ('berichten', 'persoon_id'),
  ('berichten', 'kanaal'),
  ('berichten', 'onderwerp'),
  ('berichten', 'inhoud'),
  ('berichten', 'verzonden'),
  ('instellingen', 'sleutel'),
  ('instellingen', 'waarde'),
  ('instellingen', 'gewijzigd'),
  ('logboek', 'id'),
  ('logboek', 'tijdstip'),
  ('logboek', 'soort'),
  ('logboek', 'wie'),
  ('logboek', 'wat'),
  ('logboek', 'details'),
  ('logboek', 'afgehandeld'),
  ('ouder_kind', 'ouder_id'),
  ('ouder_kind', 'kind_id'),
  ('ouder_kind', 'aangemaakt'),
  ('periodes', 'id'),
  ('periodes', 'seizoen'),
  ('periodes', 'naam'),
  ('periodes', 'van'),
  ('periodes', 'tot'),
  ('periodes', 'soort'),
  ('periodes', 'doelgroep'),
  ('periodes', 'bron'),
  ('personen', 'id'),
  ('personen', 'voornaam'),
  ('personen', 'achternaam'),
  ('personen', 'naam_vbl'),
  ('personen', 'naam_bron'),
  ('personen', 'rel_guid'),
  ('personen', 'lid_nr'),
  ('personen', 'geboortedatum'),
  ('personen', 'geboortedatum_bron'),
  ('personen', 'email'),
  ('personen', 'tel_vast'),
  ('personen', 'tel_gsm'),
  ('personen', 'gsm_delen'),
  ('personen', 'straat'),
  ('personen', 'nummer'),
  ('personen', 'bus'),
  ('personen', 'postcode'),
  ('personen', 'gemeente'),
  ('personen', 'actief'),
  ('personen', 'inactief_sinds'),
  ('personen', 'laatste_aanmeldlink'),
  ('personen', 'donkere_modus'),
  ('personen', 'kanaal_voorkeur'),
  ('personen', 'aangemaakt'),
  ('personen', 'gewijzigd'),
  ('rollen', 'id'),
  ('rollen', 'persoon_id'),
  ('rollen', 'rol'),
  ('rollen', 'team_guid'),
  ('rollen', 'seizoen'),
  ('rollen', 'bron'),
  ('rollen', 'aangemaakt'),
  ('seizoenen', 'code'),
  ('seizoenen', 'naam'),
  ('seizoenen', 'actief'),
  ('seizoenen', 'aangemaakt'),
  ('taak_runs', 'id'),
  ('taak_runs', 'taak'),
  ('taak_runs', 'gestart'),
  ('taak_runs', 'geeindigd'),
  ('taak_runs', 'status'),
  ('taak_runs', 'melding'),
  ('team_spelers', 'persoon_id'),
  ('team_spelers', 'team_guid'),
  ('team_spelers', 'seizoen'),
  ('team_spelers', 'bron'),
  ('team_spelers', 'bij_bond'),
  ('team_spelers', 'aangemaakt'),
  ('teams', 'guid'),
  ('teams', 'seizoen'),
  ('teams', 'naam'),
  ('teams', 'naam_kort'),
  ('teams', 'categorie'),
  ('teams', 'onderwijsgroep'),
  ('teams', 'gevolgd'),
  ('teams', 'selectie_aan'),
  ('teams', 'opgave_toegelaten_training'),
  ('teams', 'opgave_toegelaten_wedstrijd'),
  ('teams', 'opgave_termijn_training_uren'),
  ('teams', 'opgave_termijn_wedstrijd_uren'),
  ('teams', 'bij_bond'),
  ('teams', 'laatst_gezien'),
  ('teams', 'aangemaakt'),
  ('trainingen', 'id'),
  ('trainingen', 'team_guid'),
  ('trainingen', 'seizoen'),
  ('trainingen', 'reeks_id'),
  ('trainingen', 'datum'),
  ('trainingen', 'begin'),
  ('trainingen', 'einde'),
  ('trainingen', 'zaal_id'),
  ('trainingen', 'locatie_tekst'),
  ('trainingen', 'status'),
  ('trainingen', 'bron'),
  ('trainingen', 'handmatig_gewijzigd'),
  ('trainingen', 'opmerking'),
  ('trainingen', 'aangemaakt'),
  ('trainingsreeksen', 'id'),
  ('trainingsreeksen', 'team_guid'),
  ('trainingsreeksen', 'seizoen'),
  ('trainingsreeksen', 'weekdag'),
  ('trainingsreeksen', 'begin'),
  ('trainingsreeksen', 'einde'),
  ('trainingsreeksen', 'zaal_id'),
  ('trainingsreeksen', 'locatie_tekst'),
  ('trainingsreeksen', 'van'),
  ('trainingsreeksen', 'tot'),
  ('trainingsreeksen', 'vakantie_doorlopen'),
  ('trainingsreeksen', 'actief'),
  ('trainingsreeksen', 'aangemaakt'),
  ('wedstrijden', 'id'),
  ('wedstrijden', 'wedstrijd_guid'),
  ('wedstrijden', 'team_guid'),
  ('wedstrijden', 'seizoen'),
  ('wedstrijden', 'datum'),
  ('wedstrijden', 'begin'),
  ('wedstrijden', 'thuis'),
  ('wedstrijden', 'tegenstander'),
  ('wedstrijden', 'locatie_tekst'),
  ('wedstrijden', 'vbl_acc_guid'),
  ('wedstrijden', 'uitslag'),
  ('wedstrijden', 'status'),
  ('wedstrijden', 'wijzigingshash'),
  ('wedstrijden', 'bij_bond'),
  ('wedstrijden', 'laatst_gezien'),
  ('wedstrijden', 'selectie_gepubliceerd'),
  ('wedstrijden', 'aangemaakt'),
  ('wedstrijdselecties', 'wedstrijd_id'),
  ('wedstrijdselecties', 'persoon_id'),
  ('wedstrijdselecties', 'aangemaakt'),
  ('zaal_blokken', 'id'),
  ('zaal_blokken', 'zaal_id'),
  ('zaal_blokken', 'seizoen'),
  ('zaal_blokken', 'weekdag'),
  ('zaal_blokken', 'begin'),
  ('zaal_blokken', 'einde'),
  ('zaal_sluitingen', 'id'),
  ('zaal_sluitingen', 'zaal_id'),
  ('zaal_sluitingen', 'van'),
  ('zaal_sluitingen', 'tot'),
  ('zaal_sluitingen', 'reden'),
  ('zalen', 'id'),
  ('zalen', 'naam'),
  ('zalen', 'adres'),
  ('zalen', 'vbl_acc_guid'),
  ('zalen', 'actief'),
  ('zalen', 'open_op_feestdagen'),
  ('zalen', 'aangemaakt')
),
ontbrekend_object AS (
  SELECT v.soort AS soort, v.naam AS naam
    FROM verwacht_object v
    LEFT JOIN sqlite_master m ON m.name = v.naam AND m.type = v.soort
   WHERE m.name IS NULL
),
ontbrekende_kolom AS (
  SELECT 'kolom' AS soort, v.tabel || '.' || v.kolom AS naam
    FROM verwacht_kolom v
    LEFT JOIN pragma_table_info(v.tabel) p ON p.name = v.kolom
   WHERE p.name IS NULL
),
problemen AS (
  SELECT * FROM ontbrekend_object
  UNION ALL
  SELECT * FROM ontbrekende_kolom
)
SELECT 0 AS volgorde,
       CASE WHEN (SELECT count(*) FROM problemen) = 0
            THEN 'ALLES OK'
            ELSE (SELECT count(*) FROM problemen) || ' PROBLEEM/PROBLEMEN'
       END AS soort,
       'structuur versie 0.19.0' AS naam
UNION ALL
SELECT 1, soort, naam FROM problemen
ORDER BY volgorde, soort, naam;
